# -*- coding: utf-8 -*-
"""new_way_to create_agentic_system

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N0k6Hzx4dr-k_Ry1vrESH-z3AWUebZFX
"""

from crewai import Agent, Crew, Task, Process
from crewai.project import CrewBase, agent, task, crew, before_kickoff, after_kickoff
from crewai.agents.agent_builder.base_agent import BaseAgent
from typing import List

@CrewBase
class YourCrewName:
    """Description of your crew"""

    agents: List[BaseAgent]
    tasks: List[Task]

    # Paths to your YAML configuration files
    # To see an example agent and task defined in YAML, checkout the following:
    # - Task: https://docs.crewai.com/concepts/tasks#yaml-configuration-recommended
    # - Agents: https://docs.crewai.com/concepts/agents#yaml-configuration-recommended
    agents_config = '/content/configagents.yaml'
    tasks_config = '/content/configtasks.yaml'

    @before_kickoff
    def prepare_inputs(self, inputs):

        inputs['additional_data'] = "Some extra information"
        return inputs

    @after_kickoff
    def process_output(self, output):

        output.raw += "\nProcessed after kickoff."
        return output

    @agent
    def agent_one(self) -> Agent:
        return Agent(
            config=self.agents_config['agent_one'],
            verbose=True
        )

    @agent
    def agent_two(self) -> Agent:
        return Agent(
            config=self.agents_config['agent_two'],
            verbose=True
        )

    @task
    def task_one(self) -> Task:
      return Task(
        config=self.tasks_config['task_one'],
        agent=self.agent_one()
     )

    @task
    def task_two(self) -> Task:
      return Task(
        config=self.tasks_config['task_two'],
        agent=self.agent_two()
     )

    @crew
    def crew(self) -> Crew:
        return Crew(
            agents=self.agents,
            tasks=self.tasks,
            process=Process.sequential,
            verbose=True,
        )
YourCrewName().crew().kickoff(inputs={"any": "input here"})